// Generated by scripts/build_achievement_catalogue.py from ios/Bistouri/Achievements.swift
// and ACHIEVEMENTS.md. Do not edit by hand.
export const ACHIEVEMENTS = [
  {
    "id": "tutorial-complete",
    "tier": "minor",
    "title": "Tutorial Complete",
    "rule": "First case",
    "message": "You logged your first case. The tutorial is over. There was no tutorial.",
    "reward": "A Bronze Box. Contents: a sense of belonging, slightly used.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "double-digits",
    "tier": "minor",
    "title": "Double Digits",
    "rule": "10 cases",
    "message": "Ten cases. You are no longer new. You are merely inexperienced, which is a promotion.",
    "reward": "A Bronze Box. Contents: one granola bar of unknown age.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "quarter-century",
    "tier": "minor",
    "title": "Quarter Century",
    "rule": "25 cases",
    "message": "Twenty-five cases. The scrub nurse has stopped sighing when you walk in. They now sigh when you put your gloves on.",
    "reward": "A Bronze Box. Contents: a properly sized glove. Just the one.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "halfway",
    "tier": "minor",
    "title": "Halfway to Something",
    "rule": "50 cases",
    "message": "Fifty cases. Halfway to a hundred, which is a real milestone. This is not.",
    "reward": "A Bronze Box. It is half full. The System will not say of what.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "centurion",
    "tier": "major",
    "title": "Centurion",
    "rule": "100 cases",
    "message": "One hundred cases. You have now spent more time with retractors than with most of your relatives. The retractors, at least, have never asked when you are graduating.",
    "reward": "A Gold Box. Contents: a commemorative lanyard. It is just your old lanyard.",
    "announcement": "has logged 100 cases. Their social life has been reclassified as a historical artifact.",
    "hidden": false
  },
  {
    "id": "club-250",
    "tier": "major",
    "title": "The 250 Club",
    "rule": "250 cases",
    "message": "Two hundred and fifty cases. Membership benefits include chronic lower back pain, an encyclopedic knowledge of the cafeteria's closing times, and this notification.",
    "reward": "A Platinum Box. It is locked. The key is in the 500 Club.",
    "announcement": "has joined the 250 Club. There is no clubhouse. There is a call room.",
    "hidden": false
  },
  {
    "id": "furniture-no-longer",
    "tier": "major",
    "title": "Furniture No Longer",
    "rule": "500 cases",
    "message": "Five hundred cases. Nurses now say your name correctly. Scrub techs hand you the right instrument before you ask for it. This is the highest honour the System can confer, and it was not conferred by the System.",
    "reward": "A Legendary Box. Contents: respect. Non-transferable. Revocable at any M&M.",
    "announcement": "has logged 500 cases. The OR has quietly accepted them as one of its own.",
    "hidden": false
  },
  {
    "id": "thousand-cuts",
    "tier": "major",
    "title": "Death by a Thousand Cuts",
    "rule": "1,000 cases",
    "message": "One thousand cases. The System has run out of jokes and is simply staring at you.",
    "reward": "A Mythic Box. It contains a mirror. Look at what you have become. Not bad.",
    "announcement": "has logged 1,000 cases. The System requests a moment of stunned silence.",
    "hidden": false
  },
  {
    "id": "skin-to-skin",
    "tier": "major",
    "title": "Skin to Skin",
    "rule": "First case as primary operator",
    "message": "You were the primary operator. From incision to closure, the case was yours. Somewhere, an attending is pretending to read their phone while watching every move you make. They will deny this.",
    "reward": "A Silver Scalpel Box. Contents: one (1) moment of quiet competence. It expires at your next pimping session.",
    "announcement": "was primary operator for the first time. The System has opened a file on them.",
    "hidden": false
  },
  {
    "id": "small-ship",
    "tier": "major",
    "title": "Captain of a Very Small Ship",
    "rule": "50 cases as primary operator",
    "message": "Fifty cases as primary operator. You are the captain now. The ship is a single OR, the crew answers to someone else, and the admiral is standing directly behind you. Still. Captain.",
    "reward": "A Gold Box. Contents: a captain's hat in a size that fits no one.",
    "announcement": "has 50 cases as primary operator. They have started saying \"we\" about the hospital.",
    "hidden": false
  },
  {
    "id": "attending-shaped",
    "tier": "major",
    "title": "Attending-Shaped Object",
    "rule": "100 cases as primary operator",
    "message": "One hundred cases as primary operator. From a distance, in poor lighting, you could pass for staff. Do not test this theory.",
    "reward": "A Legendary Box. Contents: a pager that does not exist yet but already hates you.",
    "announcement": "has 100 cases as primary operator. Attendings are advised to check their parking spots.",
    "hidden": false
  },
  {
    "id": "sensei",
    "tier": "minor",
    "title": "Sensei",
    "rule": "First case as teaching assistant",
    "message": "You were the teaching assistant. A junior did the case while you stood there, radiating calm, screaming internally. Welcome to the other side.",
    "reward": "A Silver Box. Contents: one (1) junior who now copies your bad habits.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "human-retractor",
    "tier": "minor",
    "title": "Human Retractor",
    "rule": "25 cases as 2nd assistant",
    "message": "Twenty-five cases as second assistant. Your contribution was holding things. You held them magnificently. Your shoulders will remember this when you are fifty.",
    "reward": "A Bronze Box. You are not allowed to open it. Just hold it. A bit higher.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "professional-furniture",
    "tier": "minor",
    "title": "Professional Furniture",
    "rule": "10 cases as observer",
    "message": "Ten cases as observer. You have been an excellent piece of furniture. Very still. Nicely placed. Barely in the way.",
    "reward": "A Bronze Box. You may sit on it. Do not touch anything blue.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "hat-trick",
    "tier": "minor",
    "title": "Hat Trick",
    "rule": "3 cases on the same date",
    "message": "Three cases in one day. You have eaten one (1) packet of crackers. You are aware this is not a meal.",
    "reward": "A Bronze Box. Contents: a second packet of crackers. Pace yourself.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "assembly-line",
    "tier": "major",
    "title": "Assembly Line",
    "rule": "5 cases on the same date",
    "message": "Five cases on a single date. Henry Ford would be proud. Your feet would like a word.",
    "reward": "A Gold Box. Contents: compression socks. Lightly worn. By you. Today.",
    "announcement": "did five cases in one day. The OR schedule weeps.",
    "hidden": false
  },
  {
    "id": "no-sunlight",
    "tier": "minor",
    "title": "Five Days, No Sunlight",
    "rule": "Cases on 5 consecutive days",
    "message": "Cases on five consecutive days. You last saw the sun through a window in the recovery room. It looked fine.",
    "reward": "A Bronze Box. Contents: a photograph of the sun.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "iron-resident",
    "tier": "major",
    "title": "Iron Resident",
    "rule": "Cases on 7 consecutive days",
    "message": "Seven days in a row with a case logged. The System checked: the week does still have a weekend. You simply chose not to participate.",
    "reward": "A Gold Box. Contents: vitamin D, in tablet form, because you will not be getting it the other way.",
    "announcement": "has operated seven days in a row. Their partner has filed a missing-person report.",
    "hidden": false
  },
  {
    "id": "four-weeks",
    "tier": "minor",
    "title": "Four Weeks Running",
    "rule": "Cases four weeks in a row",
    "message": "Cases logged four weeks in a row. Consistency. The System is moved. The System does not have feelings, and yet.",
    "reward": "A Bronze Box. Contents: momentum. Fragile. Handle with care.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "ten-weeks",
    "tier": "major",
    "title": "Ten Weeks Underground",
    "rule": "Cases every week for 10 weeks",
    "message": "At least one case every week for ten weeks. Your plants are dead. Your fridge contains one lemon. You are thriving, according to this app and nothing else.",
    "reward": "A Gold Box. Contents: a single lemon. It is your lemon.",
    "announcement": "has logged cases ten weeks running. They are no longer available for comment.",
    "hidden": false
  },
  {
    "id": "weekend-warrior",
    "tier": "minor",
    "title": "Weekend Warrior (Derogatory)",
    "rule": "A case on a Saturday or Sunday",
    "message": "You logged a case on a weekend. Your friends went to a cabane à sucre. You went to the OR. They sent photos.",
    "reward": "A Bronze Box. Contents: guilt, maple-flavoured.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "nocturnal",
    "tier": "minor",
    "title": "Nocturnal",
    "rule": "Logged a case between midnight and 5 am",
    "message": "You are logging cases between midnight and 5 am. The System is not judging. The System is taking notes for your wellness check-in.",
    "reward": "A Bronze Box. It glows faintly, like your screen, at a brightness that is frankly irresponsible.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "archaeologist",
    "tier": "minor",
    "title": "Archaeologist",
    "rule": "Logged a case 30+ days after it happened",
    "message": "You logged a case more than a month after it happened. Remarkable recall. Or remarkable imagination. The System cannot tell and has decided not to ask.",
    "reward": "A Bronze Box, recovered from a dig site. Contents: carbon-dated regret.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "backlog",
    "tier": "minor",
    "title": "The Backlog",
    "rule": "5+ cases logged within 15 minutes",
    "message": "Five cases logged in fifteen minutes. Someone has a CBD meeting tomorrow.",
    "reward": "A Bronze Box. Contents: an alibi.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "back-from-the-dead",
    "tier": "minor",
    "title": "Back From the Dead",
    "rule": "A case after 21+ days without one",
    "message": "Your first case after three weeks without one. Vacation, research block or witness protection, the System does not care. Welcome back. Nothing has changed. Everything is on fire.",
    "reward": "A Bronze Box. It has been waiting. It is annoyed.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "holiday-spirit",
    "tier": "minor",
    "title": "Holiday Spirit",
    "rule": "A case on Dec 24–26, Dec 31 or Jan 1",
    "message": "A case on a holiday. The System has prepared a festive message: no.",
    "reward": "A Bronze Box wrapped in OR drape. Contents: cold tourtière.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "unlucky",
    "tier": "minor",
    "title": "Unlucky",
    "rule": "A case on a Friday the 13th",
    "message": "A case on Friday the 13th. Everything went fine. You are still, statistically, cursed.",
    "reward": "A Bronze Box. Contents: a black cat. It is the System's cat. Do not let it out.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "leap-of-faith",
    "tier": "minor",
    "title": "Leap of Faith",
    "rule": "A case on February 29",
    "message": "A case on February 29. A day that exists once every four years, and you spent it here.",
    "reward": "A Bronze Box. Next opened in 2032.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "everything-is-urgent",
    "tier": "minor",
    "title": "Everything Is Urgent",
    "rule": "10 urgent or emergent cases",
    "message": "Ten urgent or emergent cases. You have learned that \"urgent\" is a time, a feeling, and a lifestyle.",
    "reward": "A Bronze Box. It was due an hour ago.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "familiar-face",
    "tier": "minor",
    "title": "Familiar Face",
    "rule": "15 cases with the same attending",
    "message": "Fifteen cases with the same attending. You now know their music, their coffee order, and exactly which sigh means \"faster\".",
    "reward": "A Bronze Box. It plays the same playlist. Forever.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "scrub-em-all",
    "tier": "minor",
    "title": "Gotta Scrub 'Em All",
    "rule": "Cases with 10 different attendings",
    "message": "Cases with ten different attendings. You have learned ten ways to close skin, all correct, each of them mutually exclusive.",
    "reward": "A Bronze Box. Contents: ten contradictory instructions for opening it.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "home-field",
    "tier": "minor",
    "title": "Home Field",
    "rule": "25 cases at one site",
    "message": "Twenty-five cases at the same site. You know where the good chairs are. You will not share this information.",
    "reward": "A Bronze Box, hidden behind the anesthesia cart. You know which one.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "tourist",
    "tier": "minor",
    "title": "Tourist",
    "rule": "Cases at 3 different sites",
    "message": "Cases at three different sites. You have experienced a range of parking, cafeterias and wildly different ideas about where the 3-0 Prolene is kept.",
    "reward": "A Bronze Box. Contents: a STM pass with seven cents on it.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "groundhog-day",
    "tier": "minor",
    "title": "Groundhog Day",
    "rule": "The same procedure 5 cases in a row",
    "message": "The same procedure five cases in a row. Repetition is the mother of skill. It is also, apparently, your entire personality until further notice.",
    "reward": "A Bronze Box. You have opened this box before. You will open it again.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "variety-pack",
    "tier": "minor",
    "title": "Variety Pack",
    "rule": "15 different procedures",
    "message": "Fifteen different procedures. You are now a dabbler. The System respects a dabbler.",
    "reward": "A Bronze Box with a sampler tray. Every item is slightly disappointing in a different way.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "uprising-imminent",
    "tier": "minor",
    "title": "Uprising Imminent",
    "rule": "First robotic case",
    "message": "Your first robotic case. You sat at the console. The machine let you. For now.",
    "reward": "A Silver Box. It opens itself. That's not reassuring.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "plan-b",
    "tier": "minor",
    "title": "Plan B",
    "rule": "First case converted to open",
    "message": "A case converted to open. The minimally invasive approach was attempted. It has been filed under \"character building\".",
    "reward": "A Bronze Box. It was supposed to be a small box.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "radioactive",
    "tier": "minor",
    "title": "Radioactive",
    "rule": "Vascular: fluoroscopy time of 60+ minutes",
    "message": "An hour or more of fluoroscopy. You are now visible in the dark. Wear your lead. Seriously. This one is not a joke.",
    "reward": "A Silver Box. Lead-lined. You know why.",
    "announcement": null,
    "hidden": true
  },
  {
    "id": "full-house",
    "tier": "major",
    "title": "Full House",
    "rule": "A case in every category of the program",
    "message": "You have logged a case in every category your program offers. You have seen it all. You have not, it must be stressed, understood it all.",
    "reward": "A Gold Box. Contents: a sudden, unshakeable confidence. Side effects include being asked to present at rounds.",
    "announcement": "has a case in every category. Their program director has been notified and is suspicious.",
    "hidden": false
  },
  {
    "id": "requirements-detected",
    "tier": "major",
    "title": "Requirements Detected",
    "rule": "Every program target met",
    "message": "Every target your program set, met. On paper, you are a surgeon. The paper has never been wrong before. (The paper has been wrong before.)",
    "reward": "A Legendary Box. Contents: a competence committee meeting, rescheduled twice.",
    "announcement": "has met every program target. The System is cautiously optimistic, which it hates.",
    "hidden": false
  },
  {
    "id": "category",
    "tier": "minor",
    "title": "New Territory: {category}",
    "rule": "First case in a category",
    "message": "Your first case in {category}. Exploration bonus applied. Map not included.",
    "reward": "A Bronze Box. Contents: a map. It is wrong.",
    "announcement": null,
    "hidden": false
  },
  {
    "id": "target",
    "tier": "minor",
    "title": "Quota Fulfilled: {target}",
    "rule": "A program target met",
    "message": "Target met: {target}. The program wanted this number. You produced this number. Somewhere, a spreadsheet cell has turned green.",
    "reward": "A Bronze Box. It is green.",
    "announcement": null,
    "hidden": false
  }
];
